const DEVICE_ID_KEY = 'DEVICE_ID';
const FIREBASE_PATH = 'BILLIARD_SCORE';
const PATH_KEY = 'BILLIARD_SCORE_PATH';
const GAME_STATE_KEY = 'BILLIARD_SCORE_GAME_STATE';

const PROFILE_ID_PREFIX = 'PROFILE-';
const PROFILE_KEY  = 'PROFILE';

const CURRENCY_NUMBER_KEY = 'CURRENCY_NUMBER';
export {
    DEVICE_ID_KEY,
    FIREBASE_PATH,
    PATH_KEY,
    PROFILE_ID_PREFIX,
    PROFILE_KEY,
    GAME_STATE_KEY,
    CURRENCY_NUMBER_KEY
}