const DEVICE_ID_KEY = 'DEVICE_ID';
const FIREBASE_PATH = 'BILLIARD_SCORE';
const PATH_KEY = 'BILLIARD_SCORE_PATH';
const SERVER_KEY = 'BILLIARD_SCORE_SERVER';
const GAME_STATE_KEY = 'BILLIARD_SCORE_GAME_STATE';

const PROFILE_ID_PREFIX = 'PROFILE-';
const PROFILE_KEY  = 'PROFILE';
export {
    DEVICE_ID_KEY,
    FIREBASE_PATH,
    PATH_KEY,
    PROFILE_ID_PREFIX,
    PROFILE_KEY,
    SERVER_KEY,
    GAME_STATE_KEY
}